package pso;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import pso.Edge;

public class Graph {
	public Map<String, Node> nodeMap = new HashMap<String, Node>();
	public List<Edge> edgeList = new ArrayList<Edge>();

	@Override
	/**
	 * A graphic representation of this candidate can be generated by saving this description to a .dot file and
	 * running the command "dot -Tpng filename.dot -o filename.png"
	 */
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("digraph g {");
		for(Edge e: edgeList) {
			builder.append(e);
			builder.append("; ");
		}
		builder.append("}");
		return builder.toString();
	}

}
